# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 08:50
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20170607_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=DjangoUeditor.models.UEditorField(verbose_name='内容\t'),
        ),
    ]
